# Generated by Django 3.2.13 on 2022-08-23 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='category',
        ),
    ]
